VKBot:
  name: "VKBot"
  token: "vk1.a.bC_SF5hEzxiCJXK5RtcpNWJPkDszDFaFtj5kQyG6v8GIFGD3anqDkaYnOk0r5TkxCarYa_8e2V2BnCnOkOtIcQVh7czwah76ilZhfr8ZpZJZ4oqvB_YE9dDNskS5rkaX5yg67AXgvQim1LD6prYkJBgmyNFvPHFO4IVzhsyfAktSDq81QROTIy2zvsIVPmmK3YbOlANSb_EkA1RjSAGxnQ"